### ISSUE TITLE
To do unsupported keywords in documentation 

### ISSUE THREAD

**Issue by stefano2734** [calculix/pygccx#4]
**Is your feature request related to a problem? Please describe.**

Not supported keywords are actual not documented.

**Describe the solution you'd like**

here is a tool to see abaqus and calculix keywords
https://github.com/calculix/new_keywords

So it is simple to document the actual unsupported keywords of calculix in the actual version.
Version 2.21 of calculix is in this tool here not done and should be done.
http://www.dhondt.de/new_calc.htm

**Describe alternatives you've considered**

**Additional context**

**Comment by FrozenWinterheart** [comment]
Done. See unsupported_keywords.md as well as links in readme.
